version: '2'

services:
  nodejs_app:
    container_name: nodejs_app
    hostname: HOST_NAME-nodejs_app
    image: appdynamics/nodejs-app
    env_file: 
      - ./env.sh
    ports: 
      - "3000:3000"

  python_app:
    container_name: python_app
    hostname: HOST_NAME-python_app
    image: appdynamics/python-app
    env_file: 
      - ./env.sh
    ports: 
      - "3001:9000"

  php_app:
    container_name: php_app
    hostname: HOST_NAME-php_app
    image: appdynamics/php-app
    env_file: 
      - ./env.sh
    ports: 
      - "3002:80"

  java_app:
    container_name: java_app
    hostname: HOST_NAME-java_app
    env_file: 
      - ./env.sh
    image: appdynamics/java-app
    ports:
      - "3003:8080"

  webserver:
    container_name: webserver
    hostname: HOST_NAME-webserver
    env_file: 
      - ./env.sh
    image: appdynamics/webserver
    ports:
      - "3004:80"

  mixapp_load:
    container_name: mixapp_load
    hostname: HOST_NAME-mixapp_load
    env_file: 
      - ./env.sh
    image: appdynamics/mixapp-load
    external_links:
      - webserver
      - java-app
      - nodejs_app
      - python_app
      - php_app
      
